services:
  database:
    image: mariadb:latest
    container_name: tcc-ifrs-database
    restart: always
    environment:
      MARIADB_USER: user
      MARIADB_PASSWORD: password
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - "./database:/var/lib/mysql"
    ports:
      - 3306:3306
