spring:
  application:
    name: tcc-ifrs
  datasource:
      url: jdbc:mariadb://localhost:3306/tcc_ifrs
      username: root
      password: root
      driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
server:
  port: 8080
logging:
  level:
    com.gabrielanceski.tccifrs: DEBUG
    org.springframework.security: INFO

jwt:
  public-key: classpath:public.pub
  private-key: classpath:private.key